chore: Support macOS Desktop NativeAOT
Context: https://github.com/unoplatform/uno/commit/1003d8cf5ae9b5e6dbb2e0148a41a4a7c04fa40a

What do we want?  NativeAOT support!

Where do we want it!  Desktop macOS?

(It works for Android, how hard could desktop macOS be?)

*Allow* building with .NET 10 RC2:

	cat >patch <<EOF
	diff --git a/Chefs/Chefs.csproj b/Chefs/Chefs.csproj
	index b1fc80fc..4e181980 100644
	--- a/Chefs/Chefs.csproj
	+++ b/Chefs/Chefs.csproj
	@@ -1,4 +1,4 @@
	-﻿<Project Sdk="Uno.Sdk">
	+﻿<Project Sdk="Uno.Sdk.Private">
	 	<PropertyGroup>
	 		<!-- Building with dotnet build -f net9.0-platform will still cause restore to happen for all TargetFrameworks -->
	 		<!-- which will force us to install all workloads even if not needed -->
	diff --git a/global.json b/global.json
	index 7f65a2cc..36721321 100644
	--- a/global.json
	+++ b/global.json
	@@ -1,8 +1,8 @@
	 {
	   "msbuild-sdks": {
	-    "Uno.Sdk": "6.3.28"
	+    "Uno.Sdk.Private": "6.4.0-dev.244"
	   },
	   "sdk": {
	-    "allowPrerelease": false
	+    "allowPrerelease": true
	   }
	 }
	EOF
	git apply < patch

Build it with .NET 10 RC2:

	dotnet publish -c Release -r osx-x64 \
	  -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop \
	  -p:SelfContained=true -p:PublishAot=true -p:UseSkiaRendering=true \
	  Chefs/Chefs.csproj -bl

Run it:

	Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs

Watch it blow up (?!):

	Unhandled exception. System.DllNotFoundException: Unable to load shared library 'USER32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
	dlopen(…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll.dylib, 0x0001): tried: '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll.dylib' (no such file), '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll.dylib' (no such file)
	dlopen(USER32.dll.dylib, 0x0001): tried: 'USER32.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSUSER32.dll.dylib' (no such file), '/usr/lib/USER32.dll.dylib' (no such file, not in dyld cache), 'USER32.dll.dylib' (no such file)
	dlopen(…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll.dylib, 0x0001): tried: '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll.dylib' (no such file), '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll.dylib' (no such file)
	dlopen(libUSER32.dll.dylib, 0x0001): tried: 'libUSER32.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibUSER32.dll.dylib' (no such file), '/usr/lib/libUSER32.dll.dylib' (no such file, not in dyld cache), 'libUSER32.dll.dylib' (no such file)
	dlopen(…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll, 0x0001): tried: '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OS…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll' (no such file), '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/USER32.dll' (no such file)
	dlopen(USER32.dll, 0x0001): tried: 'USER32.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSUSER32.dll' (no such file), '/usr/lib/USER32.dll' (no such file, not in dyld cache), 'USER32.dll' (no such file)
	dlopen(…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll, 0x0001): tried: '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OS…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll' (no such file), '…/uno.chefs/Chefs/bin/Release/net10.0-desktop/osx-x64/publish/libUSER32.dll' (no such file)
	dlopen(libUSER32.dll, 0x0001): tried: 'libUSER32.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibUSER32.dll' (no such file), '/usr/lib/libUSER32.dll' (no such file, not in dyld cache), 'libUSER32.dll' (no such file)

	   at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String) + 0x46
	   at Internal.Runtime.CompilerHelpers.InteropHelpers.FixupModuleCell(InteropHelpers.ModuleFixupCell*) + 0x12c
	   at Internal.Runtime.CompilerHelpers.InteropHelpers.ResolvePInvokeSlow(InteropHelpers.MethodFixupCell*) + 0x35
	   at Windows.Win32.PInvoke.<SetProcessDpiAwarenessContext>g__LocalExternFunction|247_0(DPI_AWARENESS_CONTEXT) + 0x22
	   at Windows.Win32.PInvoke.SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT) + 0x1b
	   at DpiBootstrap.Init() + 0x10
	   at Internal.Runtime.CompilerHelpers.StartupCodeHelpers.RunInitializers(TypeManagerHandle, ReadyToRunSectionType) + 0x45
	   at Internal.Runtime.CompilerHelpers.StartupCodeHelpers.RunModuleInitializers() + 0x37
	zsh: abort      Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs

What's happening is:

 1. unoplatform/uno@1003d8cf introduced the use of module initializers
    into `Uno.UI.Runtime.Skia.Win32.Support.dll`.

 2. *Because* `Program.cs` has a `.UseWin32()` method invocation, there
    is (eventually) an assembly reference to
    `Uno.UI.Runtime.Skia.Win32.Support.dll`.

 3. Under NativeAOT, [module initializers are run during startup][0].
    ***All*** of them.

Which means that when building a NativeAOT app for macOS, the module
initializers from `Uno.UI.Runtime.Skia.Win32.Support.dll` are executed.

The "fix" (workaround) is to *remove* the call to `.UseWin32()`.

(A *better* fix would be to remove the module initializer, maybe?)

Update the `AdjustCalabash` target to update `$(DefineConstants)` based
on the `$(RuntimeIdentifier)` value, when set, so that it contains a
"#define-safe" `RUNTIME_IDENTIFIER_`-prefixed value based on
`$(RuntimeIdentifier)`.  For example, in `dotnet build -r osx-x64`,
both `RUNTIME_IDENTIFIER_OSX` and `RUNTIME_IDENTIFIER_OSX_X64` will be
defined during compilation.

See also the [.NET RID Catalog][1], from which we see that the
`$(RuntimeIdentifier)` values for Windows begin with `win-`.

Surround the `.UseWin32()` invocation with `RUNTIME_IDENTIFIER_WIN`,
so that it isn't called when running on e.g. macOS.

That fixes the `DllNotFoundException`.

The next problem is that, while it no longer crashes, it doesn't
*show* anything either.

Update `Program.cs` to call `App.InitializeLogging()`, so that we can
see log messages printed to `stdout`.

*Now* we can see the next problem:

	System.InvalidOperationException: A suitable constructor for type 'Uno.Extensions.Navigation.Navigators.ContentControlNavigator' could not be located.
	  Ensure the type is concrete and services are registered for all parameters of a public constructor.
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, ServiceIdentifier, Type, CallSiteChain) + 0x3e9
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateExact(ServiceDescriptor, ServiceIdentifier, CallSiteChain, Int32) + 0x181
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier, CallSiteChain) + 0x14f
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain) + 0xc9
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier, CallSiteChain) + 0x92
	   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier) + 0x68
	   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0xd2
	   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x39
	   at Uno.Extensions.Navigation.NavigatorFactory.CreateService(IRegion) + 0xe2
	   at Uno.Extensions.Navigation.Regions.NavigationRegion.InitializeRootRegion(IServiceProvider) + 0x61
	   at Uno.Extensions.Navigation.Regions.NavigationRegion..ctor(ILogger, FrameworkElement, IServiceProvider) + 0x2ee
	   at Uno.Extensions.Navigation.FrameworkElementExtensions.HostAsync(FrameworkElement, IServiceProvider, String, Type, Type, Func`3) + 0xbc
	   at Uno.Extensions.ServiceProviderExtensions.<BuildAndInitializeHostAsync>d__5.MoveNext() + 0x18f

Which is where everything goes off the rails: the Chefs app is
quite dynamic, whereas NativeAOT *isn't*; the trimmer is removing
lots of "necessary" code.

Square that circle by (more or less) preserving "everything": add a
`@(TrimmerRootAssembly)` item group which lists (almost) everything
that the trimmer needs to preserve.  (And then some.  This is *not*
a minimal group; this is the "biggest small" group I could get building
and running properly in a short timeframe.  It likely can be shrunk.)

Notably absent: everything that references
`Uno.UI.Runtime.Skia.Win32.Support.dll` (need to allow the app to
start!), all `System` assemblies, lots of `Microsoft.*` assemblies…

*Now* the app is able to launch and run correctly.

…but at what cost?

`Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs` is a 121MB
binary.

The `Chefs/bin/Release/net10.0-desktop/osx-x64/publish` directory is
810MB in size, though that also contains artifacts that don't appear
relevant for macOS, e.g. `libvlc/win-x64`; the `libvlc` directory
is 197MB, and doesn't immediately appear to be needed (i.e. the app
launches and is usable if `libvlc` doesn't exist).

Compare to a `-p:SelfContained=true` build which *doesn't* use
NativeAOT, and we get:

| Configuration                               |          `Chefs` size |  `publish` size |
| ------------------------------------------- | --------------------: | --------------: |
| `-p:SelfContained=true`                     |        92856 <br> 91K |            444M |
| `-p:SelfContained=true -p:PublishAot=true`  |   126703200 <br> 121M |            810M |

The non-NativeAOT build *also* contains a `libvlc` directory…

The next obvious question is "what does startup look like?"
Unfortunately that information doesn't appear to be collected by the
operating system, so I either use a stopwatch (lol) or by "feels".
NativeAOT "feels" faster, but it's not dramatic.  It feels hundredths
of a second faster to start and react to button clicks.

[0]: https://github.com/dotnet/runtime/blob/b1cb4c502f1eec66227a31e705934fb67fc091f0/src/coreclr/nativeaot/Common/src/Internal/Runtime/CompilerHelpers/StartupCodeHelpers.cs#L163-L169]
[1]: https://learn.microsoft.com/en-us/dotnet/core/rid-catalog